### PR TITLE
Do not use selinux package in runc

### PR DESCRIPTION
**Pull request by hqhq**
runc will remove it.

Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by jonboulle** [comment]
lgtm

**Comment by mrunalp** [comment]
LGTM
cc: @rhatdan @runcom

**Comment by runcom** [comment]
LGTM but the repo is going to change name to just "opencontainers/selinux". You might want to wait for that (just needs merging) before merging this one.

**Comment by caniszczyk** [comment]
repo has been renamed already

**Comment by hqhq** [comment]
Updated.

**Comment by mrunalp** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Pull request merged**
