### PR TITLE
go-selinux: fix lint

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
DO NOT MERGE YET, want to understand why go lint didn't catch those errors before

**Comment by runcom** [comment]
alright, @mrunalp @rhatdan PTAL - basically `make lint` wasn't exiting with != 0 which makes Travis green even if there are golint failures. https://github.com/opencontainers/selinux/pull/13/commits/ca27f4a84f35455d0d942d9144451c532e03e78b fixes it

**Comment by rhatdan** [comment]
👍

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
