### PR TITLE
ci: switch from travis to github actions

### PR DESCRIPTION
**Pull request by kolyshkin**
As travis-ci.org is being shot, we need a new CI.

This is a more or less one to one replacement of
Travis functionality, except there are no ppc64 machines
available (cross-compilation is still tested).

### CODE REVIEW

**Comment by kolyshkin** [comment]
No longer a WIP

**Comment by kolyshkin** [comment]
(once merged, I'll take care of removing travis job as required, and add gha jobs)

**Comment by thaJeztah** [comment]
Didn't do a full review yet, but before we forget, we need to mark these checks as "required" in the repository settings.

I also suggest to disable the "squash and merge" and "rebase and merge" options (mostly personal preference, as they clobber the contributor's commits, and with that, their GPG signing)

We could try enabling the "auto merge" option that's in beta (merge after required checks complete)

**Comment by rhatdan** [comment]
LGTM
But looks like you need a rebase.

**Comment by kolyshkin** [comment]
Rebased

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Comment by kolyshkin** [comment]
> (once merged, I'll take care of removing travis job as required, and add gha jobs)

DONE

**Pull request merged**
