### PR TITLE
Add CODEOWNERS

### PR DESCRIPTION
**Pull request by jdolitsky**

### CODE REVIEW

**Review by rhatdan — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
@kolyshkin @thaJeztah @mrunalp PTAL

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Not a blocker, but I'm still a bit on the fence on the added value of the CODEOWNERS file, as that file mostly adds value for more "mono-repos", where specific parts of the code have "owners". In this repository, that's not the case, so it rather duplicates the MAINTAINERS file (but will have to be kept in sync); also see https://github.com/opencontainers/go-digest/pull/70#issuecomment-966546705

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
