### PR TITLE
remove vendor directory

### PR DESCRIPTION
**Pull request by thaJeztah**
- follow-up to / depends on https://github.com/opencontainers/selinux/pull/183

Using a vendor directory is common for repositories that produce binaries,
but usually not for library-only repositories. Having a vendor directory
can be useful to review changes in dependencies, but as this repository
only has a single dependency (which is well-known and (usually) requires
minimal review), it's probably ok to drop the vendor directory.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@kolyshkin @giuseppe @vrothberg @mrunalp PTAL

**Comment by rhatdan** [comment]
@lsm5 PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
We probably need https://github.com/opencontainers/selinux/pull/183 first (this one includes those changes, but I can  rebase it after that).

**Comment by thaJeztah** [comment]
rebased; this should be ready for review now, PTAL 👍

**Pull request merged**
