### PR TITLE
make vendor: fix

### PR DESCRIPTION
**Pull request by kolyshkin**
This fixes Makefile's `vendor` target, and updates the vendor.

Please see individual commits for details. Spoiler alert: some commits are rather entertaining.

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

`GO111MODULE=off` was set to make sure that all Go commands use the vendor directory instead of fetching the dependencies to the module cache. Since 1.14 Go defaults to `-mod=vendor` when there's a ./vendor directory which is a very welcome change.

**Comment by rhatdan** [comment]
LGTM

**Comment by kolyshkin** [comment]
> GO111MODULE=off was set to make sure that all Go commands use the vendor directory.

right, thanks!

**Pull request merged**
