### PR TITLE
Move golang bindings to a golang subdir

### PR DESCRIPTION
**Pull request by rhatdan**
If we want to add container-selinux package to this repo, we need to move
the golang bindings to a golang subdir.

### CODE REVIEW

**Comment by rhatdan** [comment]
@mrunalp @runcom PTAL
How do you get the go tests to run in the selinux/golang directory?

**Comment by mrunalp** [comment]
go test /path/to/pkg
Or 
go test ./...  For all packages

**Comment by crosbymichael** [comment]
Usually go package names are something like `go-selinux`, `selinux-go` or anything but having `golang` in the name ;)

**Comment by runcom** [comment]
Agree with Michael

**Comment by rhatdan** [comment]
Renamed to selinux/go-selinux, now should I add a Makefile to run the tests?

**Comment by mrunalp** [comment]
@rhatdan :+1: to adding a Makefile for running tests.

**Pull request closed without merging**
