### PR TITLE
Add Go 1.20 support; require Go 1.19; drop Go 1.17 and 1.18

### PR DESCRIPTION
**Pull request by austinvazquez**
Signed-off-by: Austin Vazquez <macedonv@amazon.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
I agree we should move to 1.19 and 1.20

**Comment by austinvazquez** [comment]
I had missed bumping the version for test-stubs/golangci-lint. Should be addressed now.

**Comment by rhatdan** [comment]
LGTM

**Comment by austinvazquez** [comment]
Oh it looks like I have confused the GitHub UI. Right now it is showing the Go 1.17 and 1.18 checks as pending, but we have removed those from the testing matrix. So really the checks are green right now.

**Comment by rhatdan** [comment]
@kolyshkin @thaJeztah PTAL

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by kolyshkin** [comment]
(I've changed the list of CI jobs required for merge -- removed older versions, added 1.20.x)

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
