### PR TITLE
golangci-lint: enable more linters and address linting issues

### PR DESCRIPTION
**Pull request by thaJeztah**
- follow-up to https://github.com/opencontainers/selinux/pull/189

(more coming after this, but I have ETOOMANYBRANCHES already)

### CODE REVIEW

**Comment by rhatdan** [comment]
I am ok with almost all of these, although I am not crazy about the `err:=` shadow issue.  I find it a lot easier to read

if err := foobar(); err != nil 
}

Then 
err := foobar()
if err != nil {
}

Bottom line, I think err should be handled differently then other shadowed vars.  But I am willing to live with the changes.

LGTM

**Comment by thaJeztah** [comment]
>  I am not crazy about the `err:=` shadow issue.

Yes, I'm slightly on the fence on that one as well;

- in _most_ cases, it's mostly "noise"
- ^^ that said, I'm not against doing a "once in a while" round on changing them
- ^^^ but ... that said; I've also encountered situations where an `err` was masking an `err` that was checked in a `defer()`. Admitted, those situations are rare (and usually better to have a distinct name for "special" errors).

I don't think the linter itself has a config for this, but perhaps a string match exclusion would work (see https://golangci-lint.run/usage/false-positives/#exclude-issue-by-text)

**Comment by rhatdan** [comment]
Tests are failing for go-fumpt?

**Comment by thaJeztah** [comment]
> Tests are failing for go-fumpt?

I probably need to rebase see https://github.com/opencontainers/selinux/pull/189#issuecomment-1277485676

**Comment by thaJeztah** [comment]
Rebased, and tweaked the settings to ignore "err" for shadowing 👍  PTAL

**Comment by thaJeztah** [comment]
Oh! Had one more change staged in another branch; just pushed that one as well.

**Comment by rhatdan** [comment]
Nice work @thaJeztah

**Review by vrothberg — COMMENTED** [review]
LGTM

**Pull request merged**
