### PR TITLE
Extend `build-cross` target with `riscv64` arch

### PR DESCRIPTION
**Pull request by michalbiesek**

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by thaJeztah** [comment]
can you rebase this one, once https://github.com/opencontainers/selinux/pull/202 has been merged, so that we get a fresh run of CI also on go1.21?

**Comment by michalbiesek** [comment]
> can you rebase this one, once #202 has been merged, so that we get a fresh run of CI also on go1.21?

No problem.

**Review by kolyshkin — APPROVED** [review]
LGTM

**Pull request merged**
