### PR TITLE
Add missing .0 to VERSION

### PR DESCRIPTION
**Pull request by thaJeztah**
@rhatdan PTAL 👍

### CODE REVIEW

**Comment by vrothberg** [comment]
LGTM, thanks @thaJeztah! We need to be careful when tagging the next release and not miss the semver :-)

**Comment by thaJeztah** [comment]
Yes, we're not using `go mod` yet, but having semver will likely help there 🤗

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
Thanks @thaJeztah for keeping us on our toes.

**Comment by thaJeztah** [comment]
Was closing some tabs in my browser 😂😅

**Pull request merged**
