### PR TITLE
MAINTAINERS: add Sebastiaan

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by vbatts** [comment]
cc @opencontainers/selinux-maintainers @thaJeztah

**Comment by thaJeztah** [comment]
oh! Happy to help, but I should be clear that I'm far from an expert on SELinux itself (so I'll rely on the experts in that area if things get too specific) ☺️

**Comment by rhatdan** [comment]
@thaJeztah Don't need to be an SELinux expert, I and others can take advantage of the SELinux stuff, your help on golang is appreciated.

**Comment by thaJeztah** [comment]
> I and others can take advantage of the SELinux stuff, your help on golang is appreciated.

SGTM, thanks!

**Pull request merged**
