### PR TITLE
WIP: *: refactor to use strong types

### PR DESCRIPTION
**Pull request by runcom**
Will take care of #14 

- [ ] get rid of all the proxy functions in the `label` pkg, just use `selinux` no?
- [ ] the `state` struct in `selinux` smells
- [ ] OTHERS

This is heavy WIP and I don't expect we'll finish it anytime soon, but it's to start discussing what @cpuguy83 proposed. We need to work together to ensure a pretty interface for pkg users as, right now, it's pretty awful.

@cpuguy83 @mrunalp @rhatdan PTAL

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
@cpuguy83 how would you use the new `Label` and/or `Context` struct? in `daemon/create.go`? Will `HostConfig` have a strong type for the `SecurityOpts` field?

**Comment by cpuguy83** [comment]
@runcom Docker will continue to have to support the sec-opt format sadly, but at least we can parse into the new type.
With moby-project a more well structured API is on the table for sure.

**Comment by rhatdan** [comment]
@runcom Could you get this rebased and we can take a look at it,

**Comment by rhatdan** [comment]
Closing since this never moved forward.

**Pull request closed without merging**
