### PR TITLE
Relabel: relabel links instead of their targets

### LINKED ISSUE #172: recursive Relabel() skips symlinks
**Problem**

As described in the comment, `Relabel()` should recursively change the SELinux label on a path and all entries beneath that path.

https://github.com/opencontainers/selinux/blob/c9f6104c1b015384e35d3e7fcad0fa3ef9f24f12/go-selinux/label/label_linux.go#L106 

Currently, it skips symlinks (and instead relabels their targets).

**Explanation**

1b18907dde2de75c9762d425c862586e1f7c438a changed the semantics of `setFileLabel()` from not-dereferencing to dereferencing symlinks before applying the label change. (It also introduced the non-dereferencing `lSetFileLabel()`: The `setFileLabel`/ `lSetFileLabel` semantics became the same as the one of the kernel syscalls `setxattr`/`lsetxattr`.)

`Relabel()` mentioned above calls (`Relabel` -> `Chcon` -> `chcon` ->) `rchcon` to get the job done. `rchcon` recursively calls `setFileLabel` on the path as well as on each item below.
https://github.com/opencontainers/selinux/blob/c9f6104c1b015384e35d3e7fcad0fa3ef9f24f12/go-selinux/rchcon.go#L13-L15

**Solution**

This should be changed to `lSetFileLabel()`.

___

**Result**

When running Kubernetes (kubelet) 1.23.4 on top of containerD 1.6.0 on a SELinux-enabled system, this causes ConfigMaps to be unusuable by normal Pods:

```
[root@node ~]# ls -laZR /var/lib/kubelet/pods/2839514d-bc4b-4521-b029-5474a9c96fc5/volumes/kubernetes.io~configmap/config
/var/lib/kubelet/pods/2839514d-bc4b-4521-b029-5474a9c96fc5/volumes/kubernetes.io~configmap/config:
total 0
drwxrwsrwx. 3 root core system_u:object_r:container_file_t:s0:c294,c792 89 Mar 17 21:48 .
drwxr-xr-x. 3 root root system_u:object_r:container_var_lib_t:s0        20 Mar 17 21:48 ..
drwxr-sr-x. 2 root core system_u:object_r:container_file_t:s0:c294,c792 36 Mar 17 21:48 ..2022_03_17_21_48_25.904560199
lrwxrwxrwx. 1 root core system_u:object_r:container_var_lib_t:s0        31 Mar 17 21:48 ..data -> ..2022_03_17_21_48_25.904560199
lrwxrwxrwx. 1 root core system_u:object_r:container_var_lib_t:s0        29 Mar 17 21:48 demo.json -> ..data/demo.json

/var/lib/kubelet/pods/2839514d-bc4b-4521-b029-5474a9c96fc5/volumes/kubernetes.io~configmap/config/..2022_03_17_21_48_25.904560199:
total 4
drwxr-sr-x. 2 root core system_u:object_r:container_file_t:s0:c294,c792  36 Mar 17 21:48 .
drwxrwsrwx. 3 root core system_u:object_r:container_file_t:s0:c294,c792  89 Mar 17 21:48 ..
-rw-r--r--. 1 root core system_u:object_r:container_file_t:s0:c294,c792 350 Mar 17 21:48 demo.json
```

(In contrast to the directories and normal files, the symlinks have not been relabeled and are therefore not readable by any process running inside of the container.)

### PR DESCRIPTION
**Pull request by rrayst**
Signed-off-by: Tobias Polley <polley@predic8.de>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@kolyshkin @thaJeztah PTAL

**Comment by thaJeztah** [comment]
@rrayst could you perhaps amend the commit message to describe what's being fixed (so that git log itself provides those details, not having to resort to GitHub)? I see you wrote some bits in the related ticket that could be used for that; https://github.com/opencontainers/selinux/issues/172#issue-1172970831

(FWIW, It's ok to remove the `fixes xxx` from the commit message itself: it's sufficient to mention it in the PR description on GitHub, and including it in the commit message often adds additional "noise" if the commit gets merged in other repositories 😅)

**Comment by rrayst** [comment]
@thaJeztah PTAL

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

@kolyshkin PTAL

**Pull request merged**
